experiment:
  db_functionality_enabled: True # must set to True to generate reports, run dctweetbot, among other functions
  inference_ckpt: "/home/speediedan/experiments/deep_classiflie/checkpoints/20200910214758/checkpoint-0.5540-22-113919.pt" # note build_swa_from_ckpts will be ignored if inference_ckpt is present
  debug:
    debug_enabled: False
data_source:
  # db_conf must be explictly specified only in dev mode or if db_conf is in a non-default location
  # db_conf: "/home/speediedan/repos/edification/deep_classiflie_db/deep_classiflie_db.yaml"
  skip_db_refresh: True