experiment:
  db_functionality_enabled: True # must set to True to generate reports, run dctweetbot, among other functions
  inference_ckpt: "/home/speediedan/experiments/deep_classiflie/checkpoints/20200816114940/checkpoint-0.0000-swa_best_2_ckpts--1-0.pt" # note build_swa_from_ckpts will be ignored if inference_ckpt is present
  debug:
    debug_enabled: False
data_source:
  # db_conf must be explictly specified only in dev mode or if db_conf is in a non-default location
  # db_conf: "/home/speediedan/repos/edification/deep_classiflie_db/deep_classiflie_db.yaml"
  skip_db_refresh: True
#trainer:
  #build_swa_from_ckpts: ['/home/speediedan/experiments/deep_classiflie/checkpoints/20200814165928/checkpoint-0.5533-20-104055.pt',
  #                       '/home/speediedan/experiments/deep_classiflie/checkpoints/20200814165928/checkpoint-0.5642-26-133785.pt']
inference:
  report_mode: True  # set to true to enable report generation
  update_perf_caches_only: False # updates perf caches only using latest report, doesn't create a new report
  rebuild_perf_cache: False # set True to (re)build perf cache (report_mode must also be True)
  rebuild_stmt_cache: False  # set True to (re)build statement cache (report_mode must also be True)
  rebuild_pred_explorer: True # set True to (re)build pred_explorer widget (instead of running reports) (report_mode must also be True)
  rebuild_pred_exp_stmt_cache: False # rebuild_pred_explorer must also be true
  rebuild_perf_explorer: True # set True to (re)build perf_explorer widget (instead of running reports) (report_mode must also be True)
  rebuild_perf_exp_cache: False # rebuild_perf_explorer must also be true