experiment:
  inference_ckpt: "/home/speediedan/experiments/deep_classiflie/checkpoints/20200816114940/checkpoint-0.0000-swa_best_2_ckpts--1-0.pt"
  db_functionality_enabled: True
  debug:
    debug_enabled: False
  tweetbot:
    enabled: True
    publish: True
#data_source:
  # db_conf must be explictly specified only in dev mode or if db_conf is in a non-default location
  # db_conf: "/home/speediedan/repos/edification/deep_classiflie_db_feat/deep_classiflie_db.yaml"
inference:
  interpret_preds: True
  rpt_hist_retention_days: 60 # additional days (not including today) to retain reports for
  tweet_pub_conf_threshold: 0.77 # override default for testing
  nontweet_pub_conf_threshold: 0.96 # override default for testing