thaw_phase_0:
- classifier.bias
- classifier.weight
- ctxt_fc.bias
- ctxt_fc.weight
- ctxt_lnorm.bias
- ctxt_lnorm.weight
- ctxt_embed.weight
thaw_phase_1:
- albert.pooler.bias
- albert.pooler.weight
thaw_phase_2:
- albert.encoder.albert_layer_groups.0.albert_layers.0.ffn_output.bias
- albert.encoder.albert_layer_groups.0.albert_layers.0.ffn_output.weight
thaw_phase_3:
- albert.encoder.albert_layer_groups.0.albert_layers.0.ffn.bias
- albert.encoder.albert_layer_groups.0.albert_layers.0.ffn.weight
- albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias
- albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight
- albert.encoder.albert_layer_groups.0.albert_layers.0.attention.dense.bias
- albert.encoder.albert_layer_groups.0.albert_layers.0.attention.dense.weight
- albert.encoder.albert_layer_groups.0.albert_layers.0.attention.value.bias
- albert.encoder.albert_layer_groups.0.albert_layers.0.attention.value.weight
- albert.encoder.albert_layer_groups.0.albert_layers.0.attention.key.bias
- albert.encoder.albert_layer_groups.0.albert_layers.0.attention.key.weight
- albert.encoder.albert_layer_groups.0.albert_layers.0.attention.query.bias
- albert.encoder.albert_layer_groups.0.albert_layers.0.attention.query.weight
- albert.encoder.albert_layer_groups.0.albert_layers.0.full_layer_layer_norm.bias
- albert.encoder.albert_layer_groups.0.albert_layers.0.full_layer_layer_norm.weight
- albert.encoder.embedding_hidden_mapping_in.bias
- albert.encoder.embedding_hidden_mapping_in.weight
- albert.embeddings.LayerNorm.bias
- albert.embeddings.LayerNorm.weight
- albert.embeddings.token_type_embeddings.weight
- albert.embeddings.position_embeddings.weight
- albert.embeddings.word_embeddings.weight
